//Functions
import {
  priceFormatter,
  footerPriceFormatter,
  salaryFormatter,
  totalGrossProfitFormatter,
  locationFormatter,
} from "../../globals/functions";

//Components


export const salesReportTableColumns = (isAdmin = false) => [
  {
    dataField: "location",
    text: "Location",
    align: "left",
    headerAlign: "left",
    footer: "TOTALS",
    formatter: locationFormatter,
  },
  {
    dataField: "sellerName",
    text: "Seller",
    sort: true,
    footer: (columnData) =>
      `${columnData.reduce((acc, item) => acc + 1, 0)} records count`,
    headerStyle: () => {
      return { width: "10%" };
    },
  },
  {
    dataField: "position",
    text: "Position",
    sort: true,
    align: "left",
    headerAlign: "left",
    footer: "",
  },
  {
    dataField: "liabilityProfit",
    text: "Liability",
    headerAlign: "right",
    formatter: priceFormatter,
    sort: true,
    align: "right",
    footer: (columnData) => columnData.reduce((acc, item) => acc + item, 0),
    footerFormatter: footerPriceFormatter,
    footerAlign: "right",
    headerStyle: () => { return { width: "8%" } },
  },
  {
    dataField: "cargoProfit",
    text: "Cargo",
    headerAlign: "right",
    formatter: priceFormatter,
    sort: true,
    align: "right",
    footer: (columnData) => columnData.reduce((acc, item) => acc + item, 0),
    footerFormatter: footerPriceFormatter,
    footerAlign: "right",
    headerStyle: () => { return { width: "8%" } },
  },
  {
    dataField: "physicalDamageProfit",
    text: "Damage",
    headerAlign: "right",
    formatter: priceFormatter,
    sort: true,
    align: "right",
    footer: (columnData) => columnData.reduce((acc, item) => acc + item, 0),
    footerFormatter: footerPriceFormatter,
    footerAlign: "right",
    headerStyle: () => { return { width: "8%" } },
  },
  {
    dataField: "wcGlUmbProfit",
    text: "WC/GL/UMB",
    headerAlign: "right",
    formatter: priceFormatter,
    sort: true,
    align: "right",
    footer: (columnData) => columnData.reduce((acc, item) => acc + item, 0),
    footerFormatter: footerPriceFormatter,
    footerAlign: "right",
    headerStyle: () => { return { width: "8%" } },
  },
  {
    dataField: "totalCharge",
    text: "Sales",
    headerAlign: "right",
    formatter: priceFormatter,
    sort: true,
    align: "right",
    footer: (columnData) => columnData.reduce((acc, item) => acc + item, 0),
    footerFormatter: footerPriceFormatter,
    footerAlign: "right",
    headerStyle: () => { return { width: "8%" } },
  },
  {
    dataField: "totalSalary",
    text: "Salary",
    headerAlign: "right",
    formatter: salaryFormatter,
    sort: true,
    align: "right",
    footer: (columnData) => columnData.reduce((acc, item) => acc + item, 0),
    footerFormatter: footerPriceFormatter,
    footerAlign: "right",
    headerStyle: () => { return { width: "8%" } },
  },
  {
    dataField: "totalSaleGrossProfit",
    text: "Sales Gross",
    headerAlign: "right",
    //formatter: totalGrossProfitFormatter,
    sort: true,
    align: "right",
    footer: (columnData) => columnData.reduce((acc, item) => acc + item, 0),
    //footerFormatter: footerTotalGrossProfitFormatter,
    footerAlign: "right",
  },
  {
    dataField: "totalSaleNetProfit",
    text: "Sales Net",
    headerAlign: "right",
    //formatter: totalGrossProfitFormatter,
    sort: true,
    align: "right",
    footer: (columnData) => columnData.reduce((acc, item) => acc + item, 0),
    //footerFormatter: footerTotalGrossProfitFormatter,
    footerAlign: "right",
  },
];

export const salesReportDefaultSorted = () => [
  { dataField: "soldAt", order: "desc" },
];
